/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longrise_jie_myapplication_JniUtils */

#ifndef _Included_com_longrise_jie_myapplication_JniUtils
#define _Included_com_longrise_jie_myapplication_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longrise_jie_myapplication_JniUtils
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_longrise_jie_myapplication_JniUtils_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
